hello:
  text: "Olá Mundo!"
  app: "Aplicacao Quarkus"


#########################################################
## DEV
#########################################################

"%dev":
   hello:
     text: "Olá Devs!"

#########################################################
## STG
#########################################################

"%stg":
   hello:
     text: "Vamos testar!"